import { atom, useAtom } from "jotai";
import { PhoneIcon, Search2Icon } from "@chakra-ui/icons";
import {
  InputGroup,
  InputLeftElement,
  Input,
  Box,
  Button,
} from "@chakra-ui/react";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { functions } from "~/utils/appwrite";
import { useContext, useState } from "react";
import { UserContext } from "~/context";
import { useMutation } from "@tanstack/react-query";
import { useRouter } from "next/router";

export const payload = atom({
  chan_4: [],
  subreddits: [],
});

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // const createCollection = api.appwrite.createCollection.useMutation();

  const [topic, setTopic] = useState<string>("");
  const [data, setData] = useState({
    chan_4: [],
    subreddits: [],
  });
  const [selected, setSelected] = useAtom(payload);

  const router = useRouter();
  // const { user } = useContext(UserContext);
  const mutfn = async ({
    functionId,
    payload,
  }: {
    functionId: string;
    payload: string;
  }) => {
    return await functions.createExecution(functionId, payload);
  };

  const mutation = useMutation({
    mutationFn: mutfn,
    onSuccess: (data) => {
      console.log(data);
    },
  });

  const handleSearch = async () => {
    try {
      const payload = JSON.stringify({ q: topic, limit: 10 });
      const { response } = await mutation.mutateAsync({
        functionId: "647ec5026b8a17bda432",
        payload,
      });

      // const { response } = await functions.createExecution(
      //   "64763af50eff7902e26b",
      //   payload
      // );

      const a = JSON.parse(response);
      console.log(a);
      setData({
        chan_4: a.chan_4,
        subreddits: a.subreddits,
      });
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Data Scrapper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box maxW={"container.lg"} mt={"20"} mx={"auto"} display={"flex"}>
          <InputGroup>
            <InputLeftElement pointerEvents="none">
              <Search2Icon color="gray.300" />
            </InputLeftElement>
            <Input
              type="text"
              placeholder="Topic"
              onChange={(e) => {
                setTopic(e.target.value);
              }}
            />
          </InputGroup>

          <Button colorScheme="teal" variant="outline" onClick={handleSearch}>
            serach
          </Button>
        </Box>
        <Link
          href={{
            pathname: "/options",
          }}
        >
          <Box
            onClick={() => {
              console.log(selected);
            }}
          >
            Next
          </Box>
        </Link>
        <Box
          maxW={"container.lg"}
          mt={"20"}
          mx={"auto"}
          display={"flex"}
          flexDirection={"column"}
        >
          {data.chan_4.map((item, idx) => {
            return (
              <Box
                key={idx}
                p={5}
                shadow="md"
                borderWidth="1px"
                // flex="1"
                borderRadius="md"
                m={"2"}
                bg={selected.chan_4.includes(item) ? "green.100" : ""}
              >
                <Box
                  onClick={() => {
                    // add the current item to setSelected
                    setSelected((prev) => {
                      return {
                        ...prev,
                        chan_4: [...prev.chan_4, item],
                      };
                    });
                  }}
                  _hover={{ cursor: "pointer" }}
                >
                  Select 4chan borads
                </Box>
                <Link href={item}>
                  <div>{item}</div>
                </Link>
              </Box>
            );
          })}
          {data.subreddits.map((item, idx) => {
            return (
              <Box
                key={idx}
                p={5}
                shadow="md"
                borderWidth="1px"
                // flex="1"
                borderRadius="md"
                m={"2"}
                bg={selected.subreddits.includes(item) ? "green.100" : ""}
              >
                <Box
                  onClick={() => {
                    setSelected((prev) => {
                      return {
                        ...prev,
                        subreddits: [...prev.subreddits, item],
                      };
                    });
                  }}
                  _hover={{ cursor: "pointer" }}
                >
                  Select subreddits
                </Box>
                <Link href={item}>
                  <div>{item}</div>
                </Link>
              </Box>
            );
          })}
        </Box>
      </main>
    </>
  );
};
`
return (
  <Box
    key={idx}
    p={5}
    shadow="md"
    borderWidth="1px"
    // flex="1"
    borderRadius="md"
    m={"2"}
    bg={selected.includes(item) ? "green.100" : ""}
  >
    <Box
      onClick={() => {
        setSelected([...selected, item]);
      }}
      _hover={{ cursor: "pointer" }}
    >
      Select
    </Box>
    <Link href={item}>
      <div>{item}</div>
    </Link>
  </Box>
);

`;

export default Home;
